version=0.1
org.gradle.jvmargs=-Xms512m -Xmx2024m --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED
org.gradle.workers.max=1
org.gradle.parallel=false