server.port: 8080

info.app.name: ${spring.application.basic-name}
info.app.description: ${spring.application.description}
info.app.version: 0.1

server.url: bioritmic.ru
server.protocol: http
server.error.path: "/error"
server.error.whitelabel.enabled: false

management:
  server.port: 8081
  endpoint.health.show-details: always
  endpoints.web.base-path: "/management/actuator"
  endpoints.web.exposure.include: configprops,env,health,info,threaddump,logfile,metrics,refresh,loggers
  metrics:
    logs:
      enabled: false
      report-frequency: 60 # in seconds
  logging:
    logstash:
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512

spring:
  application:
    basic-name: Bioritmic API
    name: ${spring.application.basic-name}
    description: Bitoritmic app
  devtools.add-properties: false
  datasource:
    master:
      host: 127.0.0.1
      port: 5432
      database: bioritmic
      r2dbc-url: r2dbc:postgresql://${spring.datasource.master.host}:${spring.datasource.master.port}/${spring.datasource.master.database}
      jpa-url: jdbc:postgresql://${spring.datasource.master.host}:${spring.datasource.master.port}/${spring.datasource.master.database}
      driver: postgresql
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
      max-connections: 25
    slave:
      host: ${spring.datasource.master.host}
      port: ${spring.datasource.master.port}
      database: ${spring.datasource.master.database}
      r2dbc-url: r2dbc:postgresql://${spring.datasource.slave.host}:${spring.datasource.slave.port}/${spring.datasource.slave.database}
      jpa-url: jdbc:postgresql://${spring.datasource.slave.host}:${spring.datasource.slave.port}/${spring.datasource.slave.database}
      driver: ${spring.datasource.master.driver}
      driver-class-name: ${spring.datasource.master.driver-class-name}
      username: ${spring.datasource.master.username}
      password:  ${spring.datasource.master.password}
      max-connections: 20
  liquibase:
    contexts: default
    change-log: classpath:db-migrations/changelog.xml
    enabled: true
  mail:
    mailbox: bioritmic.project@mail.ru
    host: smtp.mail.ru
    username: bioritmic.project
    password: password
    properties:
      mail.transport.protocol: smtp
      mail.smtp.port: 465
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
