server.error.whitelabel.enabled: true
spring:
  application:
    basic-name: Bioritmic
    name: ${spring.application.basic-name}
    description: Bitoritmic app
  devtools.add-properties: false
  datasource:
    master:
      host: 127.0.0.1
      port: 5432
      database: bioritmic
      r2dbc-url: r2dbc:postgresql://${spring.datasource.master.host}:${spring.datasource.master.port}/${spring.datasource.master.database}
      jpa-url: jdbc:postgresql://${spring.datasource.master.host}:${spring.datasource.master.port}/${spring.datasource.master.database}
      driver: postgresql
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
      max-connections: 5
    slave:
      host: ${spring.datasource.master.host}
      port: ${spring.datasource.master.port}
      database: ${spring.datasource.master.database}
      r2dbc-url: r2dbc:postgresql://${spring.datasource.slave.host}:${spring.datasource.slave.port}/${spring.datasource.slave.database}
      jpa-url: jdbc:postgresql://${spring.datasource.slave.host}:${spring.datasource.slave.port}/${spring.datasource.slave.database}
      driver: ${spring.datasource.master.driver}
      driver-class-name: ${spring.datasource.master.driver-class-name}
      username: ${spring.datasource.master.username}
      password:  ${spring.datasource.master.password}
      max-connections: 5
  liquibase:
    contexts: default
    change-log: classpath:db-migrations/changelog.xml
    enabled: true