server.error.whitelabel.enabled: false
spring.mvc.throw-exception-if-no-handler-found: true
spring.resources.add-mappings: false
server.error.path: "/error

spring:
  application:
    basic-name: Bioritmic
    name: ${spring.application.basic-name}
    description: Bitoritmic app
  devtools.add-properties: false
  datasource:
    master:
      host: 127.0.0.1
      port: 5432
      database: bioritmic
      url: r2dbc:postgresql://${spring.datasource.master.host}:${spring.datasource.master.port}/${spring.datasource.master.database}
      driver: postgresql
      username: postgres
      password: postgres
      max-connections: 5
    slave:
      host: ${spring.datasource.master.host}
      port: ${spring.datasource.master.port}
      database: ${spring.datasource.master.database}
      url: r2dbc:postgresql://${spring.datasource.slave.host}:${spring.datasource.slave.port}/${spring.datasource.slave.database}
      driver: ${spring.datasource.master.driver}
      username: ${spring.datasource.master.username}
      password:  ${spring.datasource.master.password}
      max-connections: 5
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.id.new_generator_mapping: true
      hibernate.order_updates: true
      hibernate.order_inserts: true
      hibernate.jdbc.batch_versioned_data: true
      hibernate.jdbc.fetch_size: 25
      hibernate.jdbc.batch_size: 25
      hibernate.jdbc.lob.non_contextual_creation: true
