# Develop mode: -Dspring.profiles.active=develop
spring.application.name: ${spring.application.basic-name} (Develop mode)
spring.profiles.include: default,swagger
spring.devtools.add-properties: true
spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.use_sql_comments: true
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.generate_statistics: true
logging.level.org.springframework.data.r2dbc.core.DefaultDatabaseClient: debug
logging.level.com.github.shk0da.bioritmic.api: debug

spring:
  liquibase.contexts: develop
  mail:
    host: smtp.bioritmic.com
    username: admin@bioritmic.com
    password: admin
    properties:
      mail.smtp.port: 25
      mail.smtp.auth: true
      mail.smtp.starttls.enable: false