# Develop mode: -Dspring.profiles.active=develop
spring.application.name: ${spring.application.basic-name} (Develop mode)
spring.devtools.add-properties: true
spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.use_sql_comments: false
spring.jpa.properties.hibernate.format_sql: false
spring.jpa.properties.hibernate.generate_statistics: false
logging.level.ROOT: info
logging.level.io.r2dbc.postgresql.QUERY: info
logging.level.io.r2dbc.postgresql.PARAM: info
logging.level.org.springframework.r2dbc.core.DefaultDatabaseClient: debug
logging.level.org.springframework.r2dbc.connection.R2dbcTransactionManager: debug
logging.level.com.github.shk0da.bioritmic.api: debug

server.url: localhost:8080

spring:
  liquibase.contexts: develop
  mail:
    mailbox: bioritmic.project@mail.ru
    host: smtp.mail.ru
    username: bioritmic.project
    password: password
    properties:
      mail.transport.protocol: smtp
      mail.smtp.port: 465
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
