server.port: 8082

info.app.name: ${spring.application.basic-name}
info.app.description: ${spring.application.description}
info.app.version: 0.1

server.backand.port: 8080
server.error.path: "/error"
server.error.whitelabel.enabled: false
# spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

management:
  server.port: 8083
  endpoint.health.show-details: always
  endpoints.web.base-path: "/management/actuator"
  endpoints.web.exposure.include: configprops,env,health,info,threaddump,logfile,metrics,refresh,loggers
  metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
    logs: # Reports Dropwizard metrics in the logs
      enabled: false
      report-frequency: 60 # in seconds
  logging:
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512

spring:
  application:
    basic-name: Bioritmic UI
    name: ${spring.application.basic-name}
    description: Bitoritmic app
  devtools.add-properties: false